// Copyright 2015-2023 Piperift - All rights reserved
#pragma once

#include <Pipe/Files/Paths.h>
#include <Pipe/Reflect/Struct.h>


namespace rift
{
	struct CNativeBinding : public p::Struct
	{
		P_STRUCT(CNativeBinding, p::Struct)

		P_PROP(binaries)
		p::TArray<p::String> binaries;

		P_PROP(autoGenerateDefinitions)
		bool autoGenerateDefinitions = false;
	};
}    // namespace rift
