// Copyright 2015-2024 Piperift - All rights reserved
#pragma once

#include <Pipe/Files/Paths.h>
#include <PipeReflect.h>


namespace rift
{
	struct CNativeBinding
	{
		P_STRUCT(CNativeBinding)

		P_PROP(binaries)
		p::TArray<p::String> binaries;

		P_PROP(autoGenerateDefinitions)
		bool autoGenerateDefinitions = false;
	};
}    // namespace rift
