// Copyright 2015-2023 Piperift - All rights reserved

#include "NativeBindingModule.h"

#include "Components/CNativeBinding.h"
#include "Components/Declarations.h"
#include "HeaderIterator.h"

#include <AST/Components/CFileRef.h>
#include <AST/Components/CModule.h>
#include <AST/Id.h>
#include <AST/Tree.h>
#include <AST/Utils/ModuleUtils.h>
#include <AST/Utils/TypeUtils.h>
#include <PipeArrays.h>
#include <PipeECS.h>


// P_OVERRIDE_NEW_DELETE


namespace rift
{
	struct ParsedModule
	{
		ast::Id id = ast::NoId;
		TArray<String> headers;
	};

	void NativeBindingModule::Load()
	{
		// Register types
		ast::RiftTypeSettings typeSettings{.category = "Bindings"};
		typeSettings.displayName  = "C Struct";
		typeSettings.hasVariables = true;
		typeSettings.hasFunctions = false;
		ast::RegisterFileType<CDeclCStruct>("CStruct", typeSettings);
		typeSettings.displayName       = "C Static";
		typeSettings.hasVariables      = true;
		typeSettings.hasFunctions      = true;
		typeSettings.hasFunctionBodies = false;
		ast::RegisterFileType<CDeclCStatic>("CStatic", typeSettings);
		ast::PreAllocPools<CDeclCStruct, CDeclCStatic>();

		// Register module binding
		ast::RegisterModuleBinding(
		    {.id = "C", .tagType = CNativeBinding::GetStaticType(), .displayName = "C"});
		ast::RegisterSerializedModulePools<CNativeBinding>();
		ast::PreAllocPools<CNativeBinding>();
	}

	void FindHeaders(ast::Tree& ast, TView<ParsedModule> parsedModules)
	{
		p::TAccess<ast::CFileRef> access{ast};
		for (auto& module : parsedModules)
		{
			StringView path = ast::GetModulePath(access, module.id);
			for (const auto& headerPath : HeaderIterator(path))
			{
				module.headers.Add(p::ToString(headerPath));
			}
		}
	}

	void NativeBindingModule::SyncIncludes(ast::Tree& ast)
	{
		TArray<ast::Id> moduleIds;
		p::FindAllIdsWith<ast::CModule, CNativeBinding>(ast, moduleIds);

		// Only use automatic native bindings on modules marked as such
		moduleIds.RemoveIfSwap([ast](auto id) {
			return !ast.Get<CNativeBinding>(id).autoGenerateDefinitions;
		});

		TArray<ParsedModule> parsedModules;
		parsedModules.Reserve(moduleIds.Size());
		for (i32 i = 0; i < moduleIds.Size(); ++i)
		{
			auto& parsed = parsedModules.AddRef();
			parsed.id    = moduleIds[i];
		}
		FindHeaders(ast, parsedModules);
		// TODO: Generate Rift interface
	}
}    // namespace rift
