if (${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(WINDOWS TRUE)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(LINUX TRUE)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(MACOSX TRUE)
endif()

function(target_define_platform target)
    if (WINDOWS)
        target_compile_definitions(${target} PRIVATE PLATFORM_WINDOWS=1)
        
    elseif (LINUX)
        target_compile_definitions(${target} PRIVATE PLATFORM_LINUX=1)
    elseif (MACOSX)
        target_compile_definitions(${target} PRIVATE PLATFORM_MAC=1)
    endif()
endfunction()
