name: build

on:
  push:
  pull_request:

jobs:
  Build:
    name: ${{ matrix.os-name }} (${{ matrix.compiler }})
    runs-on: windows-latest
    strategy:
      runs-on: ${{ matrix.os }}
      matrix:
        name: [windows-msvc, windows-clang, ubuntu-clang, ubuntu-gcc, macos-clang]
        include:
          - name: windows-msvc
            os: windows-latest
            os-name: windows
            compiler: msvc
            cxx: cl
            cc: cl
          - name: windows-clang
            os: windows-latest
            os-name: windows
            compiler: clang
            cxx: clang-cl
            cc: clang-cl
          - name: ubuntu-clang
            os: ubuntu-latest
            os-name: ubuntu
            compiler: clang
            cxx: clang++
            cc: clang
          - name: ubuntu-gcc
            os: ubuntu-latest
            os-name: ubuntu
            compiler: gcc
            cxx: g++-10
            cc: gcc-10
          - name: macos-clang
            os: macos-latest
            os-name: macos
            compiler: clang
            cxx: clang++
            cc: clang


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Init Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Set Compiler Environment
        uses: lukka/set-shell-env@v1
        with:
          CXX: ${{ matrix.cxx }}
          CC: ${{ matrix.cc }}

      - name: Get vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgDirectory: '${{ github.workspace }}/Extern/vcpkg'

      - name: Build Clang Debug
        uses: lukka/run-cmake@v3.3
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeBuildType: Debug
          buildWithCMakeArgs: --config Debug -- -v
          buildDirectory: 'Build'

      - name: Run Tests
        working-directory: ./Build
        run: ctest --output-on-failure -j2 -C Debug

      - name: Build Clang Release
        uses: lukka/run-cmake@v3.3
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeBuildType: Release
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: --config Release -- -v
          buildDirectory: 'Build'


      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v2
        if: ${{ matrix.compiler == 'clang'}} # Only clang artifacts are stored
        with:
          name: rift-${{ matrix.name }}
          path: Build/Bin