name: linux-cicd

on: [push, pull_request]

jobs:
  Build:
    name: Build ${{ matrix.name }} (${{ matrix.build-type }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [Clang, GCC]
        build-type: [Release, Debug]
        include:
          - name: Clang
            compiler: clang
            os: ubuntu-20.04
            cxx: clang++
            cc: clang
          - name: GCC
            compiler: gcc
            os: ubuntu-20.04
            cxx: g++
            cc: gcc

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Init Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Install dependencies
        run: sudo apt-get install build-essential xz-utils curl libx11-dev libglu1-mesa-dev libxrandr-dev

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Cache LLVM and Clang
        if: matrix.compiler == 'clang'
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-11.0
      - name: Install LLVM and Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Cache Build
        uses: actions/cache@v2
        with:
          path: Build
          key: linux-${{ matrix.compiler }}-${{ matrix.build-type }}-build-${{ secrets.VCACHE}}

      - name: Configure and Build
        uses: lukka/run-cmake@v3.3
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: 'CMakeLists.txt'
          cmakeBuildType: ${{ matrix.build-type }}
          cmakeAppendedArgs: -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
          buildWithCMakeArgs: --config ${{ matrix.build-type }}
          buildDirectory: 'Build'

      - uses: actions/upload-artifact@v2
        # Only clang artifacts are stored
        if: ${{ matrix.compiler == 'clang' && matrix.build-type == 'Release' }}
        with:
          name: linux-${{ matrix.compiler }}-build
          path: Build/Bin

      - name: Run Tests
        working-directory: ./Build
        run: ctest --output-on-failure -j2 -C ${{ matrix.build-type }}
